version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-stretch

    working_directory: ~/statsapiclient

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            - v1-dependencies-

      - run:
          name: Install System Dependencies
          command: pip install poetry

      - run:
          name: Install Project Dependencies
          command: poetry install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Run Tests 
          command: poetry run pytest
