version: 2.1

executors:
  statsapiclient-executor:
    docker:
      - image: circleci/python:3.8-buster

    working_directory: ~/statsapiclient

jobs:
  build:
    executor: statsapiclient-executor

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-{{ .Environment.PY_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Install System Dependencies
          command: pip install poetry

      - run:
          name: Install Project Dependencies
          command: poetry install

      - save_cache:
          key: venv-{{ .Environment.PY_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - .venv

      - run:
          name: Run Linter
          command: poetry run flake8 statsapiclient

      - run:
          name: Run Tests
          command: poetry run pytest

      - run:
          name: Build
          command: poetry build

      - run:
          name: Create Workspace
          command: mkdir -p workspace

      - run:
          name: Move Build for Persistence
          command: mv dist pyproject.toml workspace

      - persist_to_workspace:
          root: workspace

          paths:
            - dist
            - pyproject.toml

  deploy-test:
    executor: statsapiclient-executor

    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: Move Build for Publish
          command: mv workspace/* .

      - run:
          name: Publish to test.pypi
          command: poetry run twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --repository-url https://test.pypi.org/legacy/ dist/*

  deploy:
    executor: statsapiclient-executor

    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: Move Build for Publish
          command: mv workspace/dist .

      - run:
          name: Publish to pypi
          command: poetry publish --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/

      - approve-test:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - deploy-test:
          requires:
            - approve-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - approve-prod:
          type: approval
          requires:
           - deploy-test

      - deploy:
          requires:
            - approve-prod
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
