name: Publish

on:
  release:
    types:
      - created

jobs:
  test:
    name: Test
    uses: bplabombarda/statsapiclient/.github/workflows/_test.yml@main

  build:
    name: Build
    needs: test
    uses: bplabombarda/statsapiclient/.github/workflows/_build.yml@main

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.12

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: poetry-build
          path: dist/

      - name: Configure test pypi repository
        run: poetry config repositories.test https://test.pypi.org/legacy/

      - name: Publish Test
        run: poetry publish -r test --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction
        env:
          PYPI_USERNAME: ${{ secrets.test_pypi_username }}
          PYPI_PASSWORD: ${{ secrets.test_pypi_password }}

      - name: Configure pypi repository
        run: poetry config repositories.test https://pypi.org/legacy/

      - name: Publish
        run: poetry publish -r test --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction
        env:
          PYPI_USERNAME: ${{ secrets.pypi_username }}
          PYPI_PASSWORD: ${{ secrets.pypi_password }}