name: Publish

on: [pull_request]

jobs:
  test:
    name: Test
    uses: bplabombarda/statsapiclient/.github/workflows/_test.yml@github-actions

  build:
    name: Build
    needs: test
    uses: bplabombarda/statsapiclient/.github/workflows/_build.yml@github-actions
